### ISSUE TITLE
功能建议：添加提示某个群提交的反馈

### ISSUE THREAD

**Issue by Shadow403** [HauKuen/nonebot_plugin_report_manager#2]

**Comment by haukuen** [comment]
是在反馈时带上群名还是能向bot查看一个群的所有反馈？

**Comment by Shadow403** [comment]
我觉得是先把“群号&群名”(gid&gname)带上方便知道是那个群的问题，后期有时间可以再考虑做所有反馈

**Comment by haukuen** [comment]
这个倒是好弄，但是有人用这插件的话我还是重写一遍加点功能算了，这个太粪作了。

**Comment by Shadow403** [comment]
> 这个倒是好弄，但是有人用这插件的话我还是重写一遍加点功能算了，这个太粪作了。

倒也不至于，既然发布了，就会有价值

**Comment by Shadow403** [comment]
或者说，你可以做成一个纯转发插件用(json)储存转发人/群等信息，临时转发带参数即可(-g 群，-u 用户等)
