### ISSUE TITLE
希望可以添加在.env文件中定义多个Superuser的情况下指定回复某Superuser的功能

### ISSUE THREAD

**Issue by 2580m** [HauKuen/nonebot_plugin_report_manager#4]
### 说说你遇到的问题？

如#3

### 有什么好的想法？

如果能实现的话，希望统一在.env文件里配置

**Comment by haukuen** [comment]
ec06aaac6d3d9d04f4abc54eca2a186d11b70b2a README还没改
现在改成了 `.env` 里如果有 `feedback_users` 则只发送给这个列表里的人，没有的话发给全体管理员
如果不急的话可以先不更新，这几天改一改以前的屎，也没有适配nb的新插件要求

**Comment by 2580m** [comment]
> [ec06aaa](https://github.com/HauKuen/nonebot_plugin_report_manager/commit/ec06aaac6d3d9d04f4abc54eca2a186d11b70b2a) README还没改 现在改成了 `.env` 里如果有 `feedback_users` 则只发送给这个列表里的人，没有的话发给全体管理员 如果不急的话可以先不更新，这几天改一改以前的屎，也没有适配nb的新插件要求

好喵
